CREATE TABLE auth.sessions (
  id uuid NOT NULL PRIMARY KEY,
  user_id uuid NOT NULL,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  factor_id uuid,
  aal text,
  not_after timestamp with time zone,
  refreshed_at timestamp without time zone,
  user_agent text,
  ip inet,
  tag text
);

CREATE TABLE auth.users (
  instance_id uuid,
  id uuid NOT NULL PRIMARY KEY,
  aud character varying,
  role character varying,
  email character varying UNIQUE,
  encrypted_password character varying,
  email_confirmed_at timestamp with time zone,
  invited_at timestamp with time zone,
  confirmation_token character varying UNIQUE,
  confirmation_sent_at timestamp with time zone,
  recovery_token character varying UNIQUE,
  recovery_sent_at timestamp with time zone,
  email_change_token_new character varying UNIQUE,
  email_change character varying,
  email_change_sent_at timestamp with time zone,
  last_sign_in_at timestamp with time zone,
  raw_app_meta_data jsonb,
  raw_user_meta_data jsonb,
  is_super_admin boolean,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  phone text UNIQUE DEFAULT NULL,
  phone_confirmed_at timestamp with time zone,
  phone_change text DEFAULT '',
  phone_change_token character varying DEFAULT '',
  phone_change_sent_at timestamp with time zone,
  confirmed_at timestamp with time zone,
  email_change_token_current character varying UNIQUE DEFAULT '',
  email_change_confirm_status smallint DEFAULT 0,
  banned_until timestamp with time zone,
  reauthentication_token character varying UNIQUE DEFAULT '',
  reauthentication_sent_at timestamp with time zone,
  is_sso_user boolean NOT NULL DEFAULT false,
  deleted_at timestamp with time zone,
  is_anonymous boolean NOT NULL DEFAULT false,
  display_name character varying
);