mod soal;
mod kategori_soal;
mod paket_soal;
mod paket_soal_item;
mod paket_soal_response;
mod list_paket_soal;
pub type Soal = soal::Soal;
pub type KategoriSoal = kategori_soal::KategoriSoal;
pub type PaketSoal = paket_soal::PaketSoal;
pub type PaketSoalItem = paket_soal_item::PaketSoalItem;
pub type PaketSoalResponse = paket_soal_response::PaketSoalResponse;
pub type ListPaketSoal = list_paket_soal::ListPaketSoal;
